#!/usr/bin/env python3
"""Prepend the relaxed-lint header to the generated `cloudthinker-api` lib.rs.

progenitor output uses `.unwrap()`/`.expect()` (e.g. `Client::new`), which the
workspace's deny-by-default restriction lints would reject. The generated crate
is not hand-maintained, so it opts out at the crate root instead of inheriting
`[lints] workspace = true`. Idempotent — running twice does not double the
header (keeps `make gen` diff-free on re-run).
"""

from __future__ import annotations

import sys

HEADER = (
    "// @generated by `make gen` (progenitor) — do not edit by hand.\n"
    "#![allow(clippy::unwrap_used, clippy::expect_used, clippy::all, clippy::pedantic)]\n"
    "\n"
)
MARKER = "// @generated by `make gen`"


def main() -> None:
    if len(sys.argv) != 2:
        raise SystemExit("usage: inject_lint_header.py <lib.rs>")
    path = sys.argv[1]
    with open(path) as fh:
        body = fh.read()
    if body.startswith(MARKER):
        return
    with open(path, "w") as fh:
        fh.write(HEADER + body)
    print("inject_lint_header: header prepended")


if __name__ == "__main__":
    main()
